### ISSUE TITLE
Deduplicate - break CamelCase into words

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#107]
1. [CamelCase to underscore](https://www.codewars.com/kata/5b1956a7803388baae00003a)
- 6kyu
- Satisfaction 92% of 620 solutions
- Resulting words are separated with underscore, numbers involved
- 1 pending issue regarding code style
- 5 approved languages
- Published Jun 2018, author active

2. [Break camelCase](https://www.codewars.com/kata/break-camelcase)
- 6kyu
- empty space as separator
- 90% out of ~60k solutions
- 1 pending issue, probably invalid
- 11 languages + 5 pending translations
- published Aug 2013, author inactive

3. [Split camelcase](https://www.codewars.com/kata/split-camelcase)
- 7kyu
- empty space as separator
- 84% with 230 solutions
- 2 pending issues complaining about bugged tests
- 1 approved language
- Published Jan 2017, author active

I have not solved 1. nor 3. yet, so I cannot compare languages exactly, especially  in pending translations. I will add comparison of languages when I solve the kata.

-----

### Conclusion:

- There was no clear conclusion whether 1. and 2. are duplicates, so let's keep [CamelCase to underscore](https://www.codewars.com/kata/5b1956a7803388baae00003a) and [Break camelCase](https://www.codewars.com/kata/break-camelcase).
- [x] Retire 3. [Split camelcase](https://www.codewars.com/kata/split-camelcase).

**Comment by fcr--** [comment]
It seems like it would make sense to retain the 2nd one.

**Comment by ejini6969** [comment]
In 3. the character in front of the uppercase letter can be a space (i.e it's alr split properly) or a digit. As for 2. the character in front of the uppercase letter is guaranteed to be a lowercase letter. As for 1. the condition for separating is more complicated with single uppercase letters and digits involved! 

3 is definitely gonna go down the grave due to less completion and abit under-ranked IMO. 2 should be kept due to high completions and many languages.  I'm not sure about 1 since by looking at the solutions, the complexity adds something new but the core idea behind is still the use of lookahead & lookbehind in regex which has been introduced in many katas it seems!

**Comment by Blind4Basics** [comment]
1 has the more precise tests, with all kinds of edge cases (see sample tests), especially about underscores already being present in the input (and that must not be changed) and add a tiny twist with handling numbers as well as "words". By far, the best kata of the 3, imo. Note: I compared python only, assuming all translations are consistent...

retire 3 for sure (misranked, less precise tests, ...)
I'd prefere to see 1 survive instead of 2.

**Comment by benjaminzwhite** [comment]
Agree with Blind4Basics, kata 1 (in Python at least) has much better tests and edge cases compared to 2 (especially considering they are both 6 kyu).

Vote to retire 3 in any case though, no real interest - especially as there are so many "adjacent" kata involving some basic variation on converting cases.

**Comment by EloiseRosen** [comment]
vote for keep 1, retire 2 and 3

**Comment by monadius** [comment]
Vote to keep 1 and 2 and retire 3. 2 is essentially an easier version of 1 (which is confirmed by the number of completions). Moreover, 2 has consistent tests: camel case where the first letter is not capitalized. 1 mixes camel case, Pascal case and snake case.
