### ISSUE TITLE
Retire "Convert to Binary"

### ISSUE THREAD

**Issue by hobovsky** [codewars/content-issues#215]
Kata: [Convert to Binary](https://www.codewars.com/kata/59fca81a5712f9fa4700159a)

This kata is based on a terrible mixup of numeric values and their representations. It makes things confusing and the topic of base conversions is approached in a blatantly incorrect way.

I think there is no use in fixing the kata, because there is already a bunch of binary conversions kata, and base conversions kata. But at the same time, none of the other kata is 8 kyu. 

Please vote 👎 to retire or 👍 to keep (eventually with a proposal how to fix).

--------

Conslusion:

- Keep [Convert to Binary](https://www.codewars.com/kata/59fca81a5712f9fa4700159a), do not retire.

**Comment by KayleighWasTaken** [comment]
I see no value in fixing this, or indeed any real method to do so. Making the expected output a string (as is correct) still would provide zero educational value since it's still just a builtin in every language on the platform other than (iirc at least) the two assemblies and LC. At absolute best this should be retired and remade in those if we decide there to be enough value in compared to existing base conversion tasks.

Also thumbs up/down emojis are confusing for the votes, we voted incorrectly at first (and I believe monadius did too).

**Comment by monadius** [comment]
I like that this kata asks to return a number (not a string). It makes it more fun to solve in low level languages (C, NASM).

**Comment by hobovsky** [comment]
> Also thumbs up/down emojis are confusing for the votes, we voted incorrectly at first (and I believe monadius did too).

I do not know what other emojis to use, Github has a very limited choice of emojis which can be used as reactions.

**Comment by hobovsky** [comment]
> I like that this kata asks to return a number (not a string). It makes it more fun to solve in low level languages (C, NASM).

Would you suggest to leave it as it is? The _"... returns [input] number in a binary format"_ does not sound exatly like the thing which users are expected to do. Or is it?

**Comment by monadius** [comment]
I don't see any issues with returning a decimal representation of binary numbers. For a long time it has been a thing to represent decimal numbers by considering hex value representations as decimal values (e.g., 0x10 represents 10).

**Comment by hobovsky** [comment]
Okay this is interesting, but also good to know. Thank you for this input!

**Comment by oo01oo** [comment]
The advantage of this being 8kyu disappears in languages where converting to binary either requires you to figure out a correct algorithm or dig up a suitable function/class from your language's library. Keeping it 7kyu is more fair across the board imo, since it's a more complex task than an if-statement or hello world regardless.

**Comment by oo01oo** [comment]
The advantage of this being 8kyu disappears in languages where converting to binary either requires you to figure out a correct algorithm or dig up a suitable function/class from your language's library. Being one-line-able doesn't make it 8kyu worthy imo, otherwise most 6kyu would become 8kyu.

**Comment by wtlgo** [comment]
I think this kata is OK. The only part I would improve is the description, so it's clear that it's about converting decimal to decimal but in a different form.

**Comment by hobovsky** [comment]
Apparently this kata is not that bad as I thought, and has more value than I saw in it.

I am going to close this discussion as "KEEP".
