### ISSUE TITLE
Double submission with loads of console-logs

### ISSUE THREAD

**Issue by DelroyGayle** [codewars/content-issues#76]
Greetings

...

So I have two versions of my program submitted.
The first one full of various comments and console logs

Whilst the other is the one I meant to submit.

Please, Please
Could you delete the first one submitted 

Thank you so much

**Comment by hobovsky** [comment]
You cannot delete solutions. Some background can be found in this issue: https://github.com/codewars/codewars.com/issues/540 and other, similar ones.

**Comment by DelroyGayle** [comment]
What?? Are there no exceptions?? You can see that I have posted one after the other!
**I just want the one with loads of console logs removed.**
Surely there are exceptions to the rule. Is that not the case?

**Comment by hobovsky** [comment]
It's not a rule, it's a design decision, which in turn impacted technical capabilities.
It's kinda difficult to exceptionally delete some solutions if "Delete solution" button is not implemented.

**Comment by DelroyGayle** [comment]
Greetings 
I understand that my submission cannot be deleted
However looking at the moderation commentary you can **Hide solutions which can be considered spoilers from kata solutions page**
Also I came across a user asking for his submission to be **revoked** after he accidentally submitted a solution he had found elsewhere which he did **not** author himself. The user's request was granted.

So could you please either _hide my solution or revoke it so it does not appear at all to others_

Please would you at least do that for me?
Thanking you in advance

It does not matter to me that I lose the points, etc. I just do not want my solution visible to others.
Thank you

**Comment by JohanWiltink** [comment]
Try making your case in terms of what would be good for Codewars, or even just for the person that does what you want ( bottle of whisky? ), instead of just _what you want._ _Then_ you might get somewhere; at the moment you're not getting anywhere because people have no interest in going against _the whole design of Codewars._

What might help you in future is not clicking `Submit` but pressing `Ctrl-;` ( on Windows, might be different on Mac or Linux ), which always runs the `Submit` tests instead of submitting your solution when possible. `Ctrl-S` runs the currently visible block of tests, `Ctrl-'` runs the `Submit` tests, I think. Anyway, make the interface do what you want instead of what you say.
