### ISSUE TITLE
Hide or Revoke Submission

### ISSUE THREAD

**Issue by DelroyGayle** [codewars/content-issues#77]
Greetings

**Comment by Blind4Basics** [comment]
Hi,

Yes, that tool exists, but its goal is to hide solutions that are problematic for the community/website usage, like:
* cheats
* solutions of a harder version (kata series) submitted in easier versions
* (some other rare cases)

This feature won't be made accessible to users, because it would be an opened door for cheaters/copycats to hide there dubious actions. And the way it works right now, it won't be used for users convinence either because there are like 2M+ users nowadays, and like 10 persons only with the ability to hide something.

Cheers
