### ISSUE TITLE
Compiler to Lambda Calculus: please remove copied solution

### ISSUE THREAD

**Issue by JohanWiltink** [codewars/content-issues#8]
> Hide solutions which are valid

Apparently, mods can do this.

[Compiler to Lambda Calculus](https://www.codewars.com/kata/compiler-to-lambda-calculus/) has a single user solution, by a cheater, which is an exact copy of my own solution ( but for a single comment ).

I was _delighted_ to see I had a user solution. :smile: Then I discovered it was a cheat ( and solver was already banned ). :anguished: 

Every time I see it it breaks my heart. That kata is a labour of love I don't really expect any solutions on anymore anyway.

Can someone nuke that solution? From orbit? Just so I don't have to see it? If I don't have to look at the "Total times this kata has been completed: 2" either, that would be even greater ( but I can understand that might require completely removing the solution, which maybe can't be done ).

( If this is asking too much, for too little gain, please just close this issue. )

**Comment by Blind4Basics** [comment]
the feature is still in beta pahse, but yeah, we can try.
I'd need the link to the profile of this user, tho (could you post it privately to me on gitter, plz?)

**Comment by Blind4Basics** [comment]
note: I don't think that's the intended way to use this repository, since it's rather about a user than a kata. So this kind of thing should be posted in the old thread about [cheaters/copycats](https://github.com/Codewars/codewars.com/issues/1378)

**Comment by JohanWiltink** [comment]
I didn't know it would be about a user rather than about a kata. Apologies, but not very sincerely. How are simple users to know about the intricacies of CodeWars' internals? :]

**Comment by Blind4Basics** [comment]
no problem

(I'm not even sure myself where this should be put. End I'm not even sure that's the intended use for the "hide solution" thing: I initially suggested the feature for a completely different reason, actually. But at least, that's an occasion to try it out)

**Comment by JohanWiltink** [comment]
Yay!

**Comment by hobovsky** [comment]
> How are simple users to know about the intricacies of CodeWars' internals? :]

Things are going somewhat at a fast pace on one place, and slower in another, that's why some things are visible before they are properly announced and documented. Everything will be eventually set up, organized, explained, and announced, but there's simply not enough pairs of hands to handle all of this.

Now answering your specific points:

- solutions by plagiarists can be withdrawn by mods and reward can be revoked from a submitter. It was means as a way of penalizing plagiarists and copycats. It does not make the solution to disappear, and does not remove it from kata stats.
- new feature (from two days ago or so) is that valid *solution groups* can be hidden from solutions page. It's indented to serve as a way of preventing spoilers and "dubious", but otherwise allowed, solutions from appearing. There's no good method built around this feature yet, and it can be considered still in beta :)

There's a blog post [enqueued](https://github.com/codewars/blog/issues/20) to be prepared, which would introduce and explain how to use this, and other, features. I hope that blog feed is visible enough to be used for announcements.

**Comment by JohanWiltink** [comment]
Codewars has a blog ?!?

**Comment by hobovsky** [comment]
![image](https://user-images.githubusercontent.com/23709795/105606358-35449a80-5d99-11eb-9745-a87fc5fa477f.png)

I also think it's not visible enough. My idea would be to replace "Allies" dashboard with the blog feed, but it's just my personal idea nad I havent presented it to kazk yet. Or maybe there would be some better way to expose it and make easier to spot.

**Comment by Blind4Basics** [comment]
_(oh god, I didn't even see the feed... XD )_

**Comment by JohanWiltink** [comment]
I never go through the home page. Why not put it in the left menu? Maybe instead of the Forum - that's been superseded and will be superseded twice when `docs` goes live.

**Comment by hobovsky** [comment]
Can you create a request on [blog iboard](https://github.com/codewars/blog/issues) to expose the blog better, with your ideas? It will be nice to have opinions of other users. Would really appreciate.

**Comment by JohanWiltink** [comment]
How do I create a request? `Issue` and `Pull request` seem not to be it, `Actions` had me running away screaming.

**Comment by hobovsky** [comment]
I mean just a regular issue, which would be a feature request :) Sorry for confusing you.

**Comment by hobovsky** [comment]
Also note that copied solutions can sometimes appear in a legitimate way. For example I think one would be listed when a user unlocks solutions,  forfeits the kata, and submits a copy of existing solution to see how it works. They do not earn points or any other reward  for that, so they do not cheat. But still their solution appears in the list and I believe it's not a good candidate for being hidden.

I hate when cheaters submit solutions to kata maintained by me, so I think I can understand Johan here. It's just that things are not always clear, or need to be investigated/considered deeper.
