### ISSUE TITLE
Retire "Simple AKS Primality Test"

### ISSUE THREAD

**Issue by akar-0** [codewars/content-issues#95]
"Simple AKS Primality Test": https://www.codewars.com/kata/5416d02d932c1df3a3000492/

This kata is a mere duplicate of the too many *is_prime* katas. Nothing enforces the use of the primality test given in the description (I don't think it's actually possible to do it; and if it were, would someone be ready to work on it?) in any of the available languages (Python, Ruby and JS), and tests are at best 12 poor fixed tests.

---

### Conclusion:

- [x] Retire [Simple AKS Primality Test]( https://www.codewars.com/kata/5416d02d932c1df3a3000492/)

**Comment by JohanWiltink** [comment]
Kata should test results, not methods. It _might_ be possible to enforce a certain performance for which this particular method is necessary, but the biggest problem this kata has is not even its being a duplicate - it's its task being unsuited for a kata.

The converse task might be doable: prove a number is _not_ prime, without factoring it, and return the proof. This might take some tailoring tests, but it might be feasible to have numbers that are _infeasible_ to factor ( product of huge primes ) that fail this method _fast._ That task might make a much better kata than this one.

Nuke it.

ETA: the simplified AKS primality test is trial division in disguise. For interesting composite numbers, the proof will asymptotically take as long as trial division, because it pops up only at divisors of the number. Ie, the proof finds a prime factor. Never mind that converse kata.

**Comment by benjaminzwhite** [comment]
Just solved this, and agree with retiring -  sqrt(n) trial division for 5 kyu...

The obvious fix to "test methods rather than results" would have been to require users to actually return: 

`all the coefficients of the polynomial expansion of (x − 1)^p − (x^p − 1)` which is a bit more challenging at least.

**Comment by hobovsky** [comment]
This kata does not test what it's supposed to test.  
I am going to conclude the discussion as "Retire!".
